#!/usr/bin/env ruby

require "bundler/setup"
require "hopscotch"
require 'hopscotch/job_worker'

require_relative 'full'

class LogWorker < Hopscotch::Worker

  use_exchange Hopscotch.broker.system_exchange
  use_queue 'hopscotchLogger'
  listen_on_topic 'hopscotch.system.logger.*'

  def handle_message(message)
    puts " [x] #{message.delivery_info.routing_key}:#{message.body}"
    Hopscotch.broker.ack(message.delivery_info.delivery_tag)
  end

end

worker = LogWorker.new

worker.start!